InDE 0.0.1 build instructions
-----------------------------

   i. Requirements
  ii. Commands
 iii. Help
 
-----------------------------


i. Requirements
-----------------------------
InDE may be built on every linux system and probably on the most other
Unix-like platforms as well.

It requires the following tools to be installed before it can be built:

 - FOX >= 1.4.0 (stable branch)
 - Python >= 2.3 (older versions not tested yet)
 - SCons >= 0.93-1 (older versions not tested yet)
 - Python modules glob, os, sys and string

You can get these at:

 - http://www.fox-toolkit.org
 - http://www.python.org
 - http://www.scons.org


ii. Commands
-----------------------------
Change to the main InDE directory. Using your SVN checkout this would be:

	cd inde/trunk
	
Then, type:

	scons
	
and you will get a list of commands you can use in order to compile and
install InDE on your system. These commands are:

	Build/compile InDE: 		scons
	Install in /usr/local:		scons install
	Uninstall:					scons -c install
	Clean up:					scons -c

Besides you might want to have a look at SCons' parameters.
You can do this by typing:
	
	scons -h


iii. Help
-----------------------------
Since this is a development branch and not a stable release - it isn't even
unstable - you may not expect anything to work. Nevertheless it would be
great if you managed to report bugs, ideas and stuff.

You can do this at our berliOS project website at
	
	http://developers.berlios.de/projects/inde
	
or contact us directly by using the contact forms on our official website:

	http://inde.berlios.de

Thanks in advance!

The Double-J-Team,
Jochen Rassler and Jannis Pohlmann.
